import { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components";
import { JSX } from "react/jsx-runtime";

type RenderCardsProps = {
  data: [] | any[] | any;
  title: string;
};

const RenderCards = ({ data, title }: RenderCardsProps) => {
  console.log(data, title);
  if (data && data?.length > 0) {
    return data.map((post: JSX.IntrinsicAttributes) => (
      <Card key={post?._id} {...post} />
    ));
  }
  return (
    <h2 className="mt-5 font-bold text-[theme(colors.primaryOrange)] text-xl uppercase">
      {title}
    </h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState<string>();

  useEffect(() => {}, []);
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[theme(colors.textSecondary)] text-[16px] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormField
        // labelName="Search posts"
        // type="text"
        // name="text"
        // placeholder="Search something..."
        // value={searchText}
        // handleChange={handleSearchChange}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[theme(colors.textSecondary)] text-xl mb-3 ">
                Showing results for
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[]} title="no search results found.." />
              ) : (
                <RenderCards data={[]} title="No Posts Found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
